// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiendaOnline.Datos;

#nullable disable

namespace TiendaOnline.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240616055605_Migracion")]
    partial class Migracion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TiendaOnline.Models.Marca", b =>
                {
                    b.Property<int>("IDMARCA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDMARCA"), 1L, 1);

                    b.Property<string>("NOM_MARCA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDMARCA");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            IDMARCA = 1,
                            NOM_MARCA = "Samsung"
                        },
                        new
                        {
                            IDMARCA = 2,
                            NOM_MARCA = "Apple"
                        },
                        new
                        {
                            IDMARCA = 3,
                            NOM_MARCA = "Xiaomi"
                        });
                });

            modelBuilder.Entity("TiendaOnline.Models.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"), 1L, 1);

                    b.Property<int>("MarcaIDMARCA")
                        .HasColumnType("int");

                    b.Property<string>("Nom_Modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdModelo");

                    b.HasIndex("MarcaIDMARCA");

                    b.ToTable("Modelos");

                    b.HasData(
                        new
                        {
                            IdModelo = 1,
                            MarcaIDMARCA = 1,
                            Nom_Modelo = "Galaxy S23 Ultra"
                        },
                        new
                        {
                            IdModelo = 2,
                            MarcaIDMARCA = 1,
                            Nom_Modelo = " Galaxy Z Fold 4"
                        },
                        new
                        {
                            IdModelo = 3,
                            MarcaIDMARCA = 1,
                            Nom_Modelo = "Galaxy Watch 5 Pro"
                        },
                        new
                        {
                            IdModelo = 4,
                            MarcaIDMARCA = 1,
                            Nom_Modelo = "Galaxy Buds 2 Pro"
                        },
                        new
                        {
                            IdModelo = 5,
                            MarcaIDMARCA = 1,
                            Nom_Modelo = "QN90A Neo QLED"
                        },
                        new
                        {
                            IdModelo = 6,
                            MarcaIDMARCA = 2,
                            Nom_Modelo = "iPhone 14 Pro Max"
                        },
                        new
                        {
                            IdModelo = 7,
                            MarcaIDMARCA = 2,
                            Nom_Modelo = "Watch Series 8"
                        },
                        new
                        {
                            IdModelo = 8,
                            MarcaIDMARCA = 2,
                            Nom_Modelo = "AirPods Pro"
                        },
                        new
                        {
                            IdModelo = 9,
                            MarcaIDMARCA = 2,
                            Nom_Modelo = "AirPods Max"
                        },
                        new
                        {
                            IdModelo = 10,
                            MarcaIDMARCA = 2,
                            Nom_Modelo = "iPhone SE"
                        },
                        new
                        {
                            IdModelo = 11,
                            MarcaIDMARCA = 3,
                            Nom_Modelo = "Xiaomi 13 Pro"
                        },
                        new
                        {
                            IdModelo = 12,
                            MarcaIDMARCA = 3,
                            Nom_Modelo = "Redmi Note 12 Pro"
                        },
                        new
                        {
                            IdModelo = 13,
                            MarcaIDMARCA = 3,
                            Nom_Modelo = "True Wireless Earphones 2 Pro"
                        },
                        new
                        {
                            IdModelo = 14,
                            MarcaIDMARCA = 3,
                            Nom_Modelo = "TV Q1 75"
                        },
                        new
                        {
                            IdModelo = 15,
                            MarcaIDMARCA = 3,
                            Nom_Modelo = "Redmi Buds 4 Pro"
                        });
                });

            modelBuilder.Entity("TiendaOnline.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModeloIDMODELO")
                        .HasColumnType("int");

                    b.Property<string>("Precio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("año")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProducto");

                    b.HasIndex("ModeloIDMODELO");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("TiendaOnline.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"), 1L, 1);

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TiendaOnline.Models.Modelo", b =>
                {
                    b.HasOne("TiendaOnline.Models.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaIDMARCA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("TiendaOnline.Models.Producto", b =>
                {
                    b.HasOne("TiendaOnline.Models.Modelo", "Modelo")
                        .WithMany("Productos")
                        .HasForeignKey("ModeloIDMODELO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("TiendaOnline.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("TiendaOnline.Models.Modelo", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
